---
name: Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e., v1.0

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release --jobs 2
      - name: Compress asset
        run: |
          tar -C target/${{ matrix.target }}/release \
            -czf "fltn-${{ github.ref_name }}-${{ matrix.target }}.tar.gz" \
            fltn
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "fltn-*.tar.gz"
